build_task:
  container:
    image: gradle:jdk8
  build_script: |
    gradle build
    gradle sourceJar
    gradle shadowJar
  jar_artifacts:
    path: build/libs/**
    type: application/java-archive
